default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: milan2020
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: local_help_development

test:
  <<: *default
  database: local_help_test

production:
  <<: *default
  database: local_help_production
  username: local_help
  password: <%= ENV['LOCAL_HELP_DATABASE_PASSWORD'] %>
